spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${DB_URL}/${DB_NAME_DATABASE}?createDatabaseIfNotExist=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  config:
    import:
      - file:src/main/resources/env.properties
  jackson:
    default-property-inclusion: non_null

